version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pedidos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pedidos_db
      MYSQL_USER: pedidos_user
      MYSQL_PASSWORD: pedidos1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
